export enum ACT_FORM_FIELDS {
  NAME = "name",
  CUSTOMER = "customer",
  GENERAL_CUSTOMER = "generalCustomer",
  LAB = "lab",
  TYPE_OF_SAMPLE = "typeOfSample",
  OBJECT_NAME = "objectName",
  PLACE = "place",
  DATE_TIME = "datetime",
  METHOD = "method",
  TOOL_TYPE = "toolType",
  CLIMATIC_ENVIRONMENTAL = "climaticEnvironmental",
  PLANNING = "planning",
  NORMATIVE_DOCUMENT = "normativeDocument",
  SAMPLE_TYPE = "sampleType",
  SAMPLE = "sample",
  PREPARATIONS = "preparation",
  GOAL = "goal",
  DEFINED_INDICATORS = "definedIndicators",
  ADDITIONS = "additions",
  INFORMATION_ABOUT_SELECTION = "informationAboutSelection",
  ENVIRONMENTAL_ENGINEER = "environmentalEngineer",
  REPRESENTATIVE = "representative",
  PASSED_SAMPLE = "passedSample",
}
